/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LegendItem } from "./components/legend-component/legend-component";
export { LegendItem } from "./components/legend-component/legend-component";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PvLegendComponent {
        /**
          * The legend items
         */
        "items": LegendItem[] | string;
        /**
          * The legend title
         */
        "legendTitle"?: string;
    }
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPvLegendComponentElement extends Components.PvLegendComponent, HTMLStencilElement {
    }
    var HTMLPvLegendComponentElement: {
        prototype: HTMLPvLegendComponentElement;
        new (): HTMLPvLegendComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pv-legend-component": HTMLPvLegendComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PvLegendComponent {
        /**
          * The legend items
         */
        "items"?: LegendItem[] | string;
        /**
          * The legend title
         */
        "legendTitle"?: string;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "pv-legend-component": PvLegendComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pv-legend-component": LocalJSX.PvLegendComponent & JSXBase.HTMLAttributes<HTMLPvLegendComponentElement>;
        }
    }
}
