/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { AccordionItem } from "./components/accordion-component/accordion-component";
import { LegendItem } from "./components/legend-component/legend-component";
import { TableColumn } from "./components/table/table-component";
export { AccordionItem } from "./components/accordion-component/accordion-component";
export { LegendItem } from "./components/legend-component/legend-component";
export { TableColumn } from "./components/table/table-component";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PvAccordionComponent {
        /**
          * Allow multiple sections to be open at the same time
          * @default false
         */
        "allowMultiple": boolean;
        /**
          * The accordion items
         */
        "items": AccordionItem[] | string;
    }
    interface PvBadgeComponent {
        /**
          * If true, the badge will be filled
          * @default true
         */
        "filled": boolean;
        /**
          * If true, the badge will be rounded
          * @default false
         */
        "rounded": boolean;
        /**
          * The badge size
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The badge variant style
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'outline' | 'danger' | 'success' | 'warning';
    }
    interface PvButtonComponent {
        /**
          * If true, the button is disabled
          * @default false
         */
        "disabled": boolean;
        /**
          * If true, the button will take full width of container
          * @default false
         */
        "fullWidth": boolean;
        /**
          * The button size
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large';
        /**
          * The button variant style
          * @default 'primary'
         */
        "variant": 'primary' | 'secondary' | 'outline' | 'danger';
    }
    interface PvLegendComponent {
        /**
          * The legend items
         */
        "items": LegendItem[] | string;
        /**
          * The legend title
         */
        "legendTitle"?: string;
    }
    interface PvModalComponent {
        /**
          * Programmatically close the modal
         */
        "close": () => Promise<void>;
        /**
          * If true, clicking outside the modal will close it
          * @default true
         */
        "closeOnBackdropClick": boolean;
        /**
          * If true, pressing escape key will close the modal
          * @default true
         */
        "closeOnEscape": boolean;
        /**
          * Controls if the modal is open
          * @default false
         */
        "isOpen": boolean;
        /**
          * Modal title displayed in header
          * @default ''
         */
        "modalTitle": string;
        /**
          * Programmatically open the modal
         */
        "open": () => Promise<void>;
        /**
          * If true, close button will be shown in header
          * @default true
         */
        "showCloseButton": boolean;
        /**
          * Modal size variant
          * @default 'medium'
         */
        "size": 'small' | 'medium' | 'large' | 'fullscreen';
    }
    interface PvTableComponent {
        /**
          * The table column definitions
         */
        "columns": TableColumn[] | string;
        /**
          * The table data
         */
        "data": any[] | string;
        /**
          * Enable row deletion
          * @default false
         */
        "enableRowSelection": boolean;
        /**
          * Items to display per page
          * @default 5
         */
        "itemsPerPage": number;
    }
}
export interface PvAccordionComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPvAccordionComponentElement;
}
export interface PvButtonComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPvButtonComponentElement;
}
export interface PvModalComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPvModalComponentElement;
}
export interface PvTableComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPvTableComponentElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPvAccordionComponentElementEventMap {
        "accordionChange": any;
    }
    interface HTMLPvAccordionComponentElement extends Components.PvAccordionComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPvAccordionComponentElementEventMap>(type: K, listener: (this: HTMLPvAccordionComponentElement, ev: PvAccordionComponentCustomEvent<HTMLPvAccordionComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPvAccordionComponentElementEventMap>(type: K, listener: (this: HTMLPvAccordionComponentElement, ev: PvAccordionComponentCustomEvent<HTMLPvAccordionComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPvAccordionComponentElement: {
        prototype: HTMLPvAccordionComponentElement;
        new (): HTMLPvAccordionComponentElement;
    };
    interface HTMLPvBadgeComponentElement extends Components.PvBadgeComponent, HTMLStencilElement {
    }
    var HTMLPvBadgeComponentElement: {
        prototype: HTMLPvBadgeComponentElement;
        new (): HTMLPvBadgeComponentElement;
    };
    interface HTMLPvButtonComponentElementEventMap {
        "buttonClick": MouseEvent;
    }
    interface HTMLPvButtonComponentElement extends Components.PvButtonComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPvButtonComponentElementEventMap>(type: K, listener: (this: HTMLPvButtonComponentElement, ev: PvButtonComponentCustomEvent<HTMLPvButtonComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPvButtonComponentElementEventMap>(type: K, listener: (this: HTMLPvButtonComponentElement, ev: PvButtonComponentCustomEvent<HTMLPvButtonComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPvButtonComponentElement: {
        prototype: HTMLPvButtonComponentElement;
        new (): HTMLPvButtonComponentElement;
    };
    interface HTMLPvLegendComponentElement extends Components.PvLegendComponent, HTMLStencilElement {
    }
    var HTMLPvLegendComponentElement: {
        prototype: HTMLPvLegendComponentElement;
        new (): HTMLPvLegendComponentElement;
    };
    interface HTMLPvModalComponentElementEventMap {
        "modalOpen": void;
        "modalClose": void;
    }
    interface HTMLPvModalComponentElement extends Components.PvModalComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPvModalComponentElementEventMap>(type: K, listener: (this: HTMLPvModalComponentElement, ev: PvModalComponentCustomEvent<HTMLPvModalComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPvModalComponentElementEventMap>(type: K, listener: (this: HTMLPvModalComponentElement, ev: PvModalComponentCustomEvent<HTMLPvModalComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPvModalComponentElement: {
        prototype: HTMLPvModalComponentElement;
        new (): HTMLPvModalComponentElement;
    };
    interface HTMLPvTableComponentElementEventMap {
        "rowSort": any;
        "rowClick": any;
        "actionDelete": any;
    }
    interface HTMLPvTableComponentElement extends Components.PvTableComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPvTableComponentElementEventMap>(type: K, listener: (this: HTMLPvTableComponentElement, ev: PvTableComponentCustomEvent<HTMLPvTableComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPvTableComponentElementEventMap>(type: K, listener: (this: HTMLPvTableComponentElement, ev: PvTableComponentCustomEvent<HTMLPvTableComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPvTableComponentElement: {
        prototype: HTMLPvTableComponentElement;
        new (): HTMLPvTableComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pv-accordion-component": HTMLPvAccordionComponentElement;
        "pv-badge-component": HTMLPvBadgeComponentElement;
        "pv-button-component": HTMLPvButtonComponentElement;
        "pv-legend-component": HTMLPvLegendComponentElement;
        "pv-modal-component": HTMLPvModalComponentElement;
        "pv-table-component": HTMLPvTableComponentElement;
    }
}
declare namespace LocalJSX {
    type OneOf<K extends string, PropT, AttrT = PropT> = { [P in K]: PropT } & { [P in `attr:${K}` | `prop:${K}`]?: never } | { [P in `attr:${K}`]: AttrT } & { [P in K | `prop:${K}`]?: never } | { [P in `prop:${K}`]: PropT } & { [P in K | `attr:${K}`]?: never };

    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PvAccordionComponent {
        /**
          * Allow multiple sections to be open at the same time
          * @default false
         */
        "allowMultiple"?: boolean;
        /**
          * The accordion items
         */
        "items"?: AccordionItem[] | string;
        "onAccordionChange"?: (event: PvAccordionComponentCustomEvent<any>) => void;
    }
    interface PvBadgeComponent {
        /**
          * If true, the badge will be filled
          * @default true
         */
        "filled"?: boolean;
        /**
          * If true, the badge will be rounded
          * @default false
         */
        "rounded"?: boolean;
        /**
          * The badge size
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The badge variant style
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'outline' | 'danger' | 'success' | 'warning';
    }
    interface PvButtonComponent {
        /**
          * If true, the button is disabled
          * @default false
         */
        "disabled"?: boolean;
        /**
          * If true, the button will take full width of container
          * @default false
         */
        "fullWidth"?: boolean;
        /**
          * Emitted when the button is clicked
         */
        "onButtonClick"?: (event: PvButtonComponentCustomEvent<MouseEvent>) => void;
        /**
          * The button size
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large';
        /**
          * The button variant style
          * @default 'primary'
         */
        "variant"?: 'primary' | 'secondary' | 'outline' | 'danger';
    }
    interface PvLegendComponent {
        /**
          * The legend items
         */
        "items": LegendItem[] | string;
        /**
          * The legend title
         */
        "legendTitle"?: string;
    }
    interface PvModalComponent {
        /**
          * If true, clicking outside the modal will close it
          * @default true
         */
        "closeOnBackdropClick"?: boolean;
        /**
          * If true, pressing escape key will close the modal
          * @default true
         */
        "closeOnEscape"?: boolean;
        /**
          * Controls if the modal is open
          * @default false
         */
        "isOpen"?: boolean;
        /**
          * Modal title displayed in header
          * @default ''
         */
        "modalTitle"?: string;
        /**
          * Emitted when modal is closed
         */
        "onModalClose"?: (event: PvModalComponentCustomEvent<void>) => void;
        /**
          * Emitted when modal is opened
         */
        "onModalOpen"?: (event: PvModalComponentCustomEvent<void>) => void;
        /**
          * If true, close button will be shown in header
          * @default true
         */
        "showCloseButton"?: boolean;
        /**
          * Modal size variant
          * @default 'medium'
         */
        "size"?: 'small' | 'medium' | 'large' | 'fullscreen';
    }
    interface PvTableComponent {
        /**
          * The table column definitions
         */
        "columns"?: TableColumn[] | string;
        /**
          * The table data
         */
        "data"?: any[] | string;
        /**
          * Enable row deletion
          * @default false
         */
        "enableRowSelection"?: boolean;
        /**
          * Items to display per page
          * @default 5
         */
        "itemsPerPage"?: number;
        "onActionDelete"?: (event: PvTableComponentCustomEvent<any>) => void;
        "onRowClick"?: (event: PvTableComponentCustomEvent<any>) => void;
        "onRowSort"?: (event: PvTableComponentCustomEvent<any>) => void;
    }

    interface MyComponentAttributes {
        "first": string;
        "middle": string;
        "last": string;
    }
    interface PvAccordionComponentAttributes {
        "items": AccordionItem[] | string;
        "allowMultiple": boolean;
    }
    interface PvBadgeComponentAttributes {
        "variant": 'primary' | 'secondary' | 'outline' | 'danger' | 'success' | 'warning';
        "size": 'small' | 'medium' | 'large';
        "rounded": boolean;
        "filled": boolean;
    }
    interface PvButtonComponentAttributes {
        "variant": 'primary' | 'secondary' | 'outline' | 'danger';
        "size": 'small' | 'medium' | 'large';
        "disabled": boolean;
        "fullWidth": boolean;
    }
    interface PvLegendComponentAttributes {
        "items": LegendItem[] | string;
        "legendTitle": string;
    }
    interface PvModalComponentAttributes {
        "isOpen": boolean;
        "modalTitle": string;
        "showCloseButton": boolean;
        "closeOnBackdropClick": boolean;
        "closeOnEscape": boolean;
        "size": 'small' | 'medium' | 'large' | 'fullscreen';
    }
    interface PvTableComponentAttributes {
        "columns": TableColumn[] | string;
        "data": any[] | string;
        "itemsPerPage": number;
        "enableRowSelection": boolean;
    }

    interface IntrinsicElements {
        "my-component": Omit<MyComponent, keyof MyComponentAttributes> & { [K in keyof MyComponent & keyof MyComponentAttributes]?: MyComponent[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `attr:${K}`]?: MyComponentAttributes[K] } & { [K in keyof MyComponent & keyof MyComponentAttributes as `prop:${K}`]?: MyComponent[K] };
        "pv-accordion-component": Omit<PvAccordionComponent, keyof PvAccordionComponentAttributes> & { [K in keyof PvAccordionComponent & keyof PvAccordionComponentAttributes]?: PvAccordionComponent[K] } & { [K in keyof PvAccordionComponent & keyof PvAccordionComponentAttributes as `attr:${K}`]?: PvAccordionComponentAttributes[K] } & { [K in keyof PvAccordionComponent & keyof PvAccordionComponentAttributes as `prop:${K}`]?: PvAccordionComponent[K] };
        "pv-badge-component": Omit<PvBadgeComponent, keyof PvBadgeComponentAttributes> & { [K in keyof PvBadgeComponent & keyof PvBadgeComponentAttributes]?: PvBadgeComponent[K] } & { [K in keyof PvBadgeComponent & keyof PvBadgeComponentAttributes as `attr:${K}`]?: PvBadgeComponentAttributes[K] } & { [K in keyof PvBadgeComponent & keyof PvBadgeComponentAttributes as `prop:${K}`]?: PvBadgeComponent[K] };
        "pv-button-component": Omit<PvButtonComponent, keyof PvButtonComponentAttributes> & { [K in keyof PvButtonComponent & keyof PvButtonComponentAttributes]?: PvButtonComponent[K] } & { [K in keyof PvButtonComponent & keyof PvButtonComponentAttributes as `attr:${K}`]?: PvButtonComponentAttributes[K] } & { [K in keyof PvButtonComponent & keyof PvButtonComponentAttributes as `prop:${K}`]?: PvButtonComponent[K] };
        "pv-legend-component": Omit<PvLegendComponent, keyof PvLegendComponentAttributes> & { [K in keyof PvLegendComponent & keyof PvLegendComponentAttributes]?: PvLegendComponent[K] } & { [K in keyof PvLegendComponent & keyof PvLegendComponentAttributes as `attr:${K}`]?: PvLegendComponentAttributes[K] } & { [K in keyof PvLegendComponent & keyof PvLegendComponentAttributes as `prop:${K}`]?: PvLegendComponent[K] } & OneOf<"items", PvLegendComponent["items"], PvLegendComponentAttributes["items"]>;
        "pv-modal-component": Omit<PvModalComponent, keyof PvModalComponentAttributes> & { [K in keyof PvModalComponent & keyof PvModalComponentAttributes]?: PvModalComponent[K] } & { [K in keyof PvModalComponent & keyof PvModalComponentAttributes as `attr:${K}`]?: PvModalComponentAttributes[K] } & { [K in keyof PvModalComponent & keyof PvModalComponentAttributes as `prop:${K}`]?: PvModalComponent[K] };
        "pv-table-component": Omit<PvTableComponent, keyof PvTableComponentAttributes> & { [K in keyof PvTableComponent & keyof PvTableComponentAttributes]?: PvTableComponent[K] } & { [K in keyof PvTableComponent & keyof PvTableComponentAttributes as `attr:${K}`]?: PvTableComponentAttributes[K] } & { [K in keyof PvTableComponent & keyof PvTableComponentAttributes as `prop:${K}`]?: PvTableComponent[K] };
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.IntrinsicElements["my-component"] & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pv-accordion-component": LocalJSX.IntrinsicElements["pv-accordion-component"] & JSXBase.HTMLAttributes<HTMLPvAccordionComponentElement>;
            "pv-badge-component": LocalJSX.IntrinsicElements["pv-badge-component"] & JSXBase.HTMLAttributes<HTMLPvBadgeComponentElement>;
            "pv-button-component": LocalJSX.IntrinsicElements["pv-button-component"] & JSXBase.HTMLAttributes<HTMLPvButtonComponentElement>;
            "pv-legend-component": LocalJSX.IntrinsicElements["pv-legend-component"] & JSXBase.HTMLAttributes<HTMLPvLegendComponentElement>;
            "pv-modal-component": LocalJSX.IntrinsicElements["pv-modal-component"] & JSXBase.HTMLAttributes<HTMLPvModalComponentElement>;
            "pv-table-component": LocalJSX.IntrinsicElements["pv-table-component"] & JSXBase.HTMLAttributes<HTMLPvTableComponentElement>;
        }
    }
}
