/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { LegendItem } from "./components/legend-component/legend-component";
import { TableColumn } from "./components/table-component/table-component";
export { LegendItem } from "./components/legend-component/legend-component";
export { TableColumn } from "./components/table-component/table-component";
export namespace Components {
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
    interface PvLegendComponent {
        /**
          * The legend items
         */
        "items": LegendItem[] | string;
        /**
          * The legend title
         */
        "legendTitle"?: string;
    }
    interface PvTableComponent {
        /**
          * The table column definitions
         */
        "columns": TableColumn[] | string;
        /**
          * The table data
         */
        "data": any[] | string;
        /**
          * Enable row deletion
          * @default false
         */
        "enableRowSelection": boolean;
        /**
          * Items to display per page
          * @default 5
         */
        "itemsPerPage": number;
    }
}
export interface PvTableComponentCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLPvTableComponentElement;
}
declare global {
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLPvLegendComponentElement extends Components.PvLegendComponent, HTMLStencilElement {
    }
    var HTMLPvLegendComponentElement: {
        prototype: HTMLPvLegendComponentElement;
        new (): HTMLPvLegendComponentElement;
    };
    interface HTMLPvTableComponentElementEventMap {
        "rowSort": any;
        "rowClick": any;
        "actionDelete": any;
    }
    interface HTMLPvTableComponentElement extends Components.PvTableComponent, HTMLStencilElement {
        addEventListener<K extends keyof HTMLPvTableComponentElementEventMap>(type: K, listener: (this: HTMLPvTableComponentElement, ev: PvTableComponentCustomEvent<HTMLPvTableComponentElementEventMap[K]>) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | AddEventListenerOptions): void;
        addEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | AddEventListenerOptions): void;
        removeEventListener<K extends keyof HTMLPvTableComponentElementEventMap>(type: K, listener: (this: HTMLPvTableComponentElement, ev: PvTableComponentCustomEvent<HTMLPvTableComponentElementEventMap[K]>) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof DocumentEventMap>(type: K, listener: (this: Document, ev: DocumentEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener<K extends keyof HTMLElementEventMap>(type: K, listener: (this: HTMLElement, ev: HTMLElementEventMap[K]) => any, options?: boolean | EventListenerOptions): void;
        removeEventListener(type: string, listener: EventListenerOrEventListenerObject, options?: boolean | EventListenerOptions): void;
    }
    var HTMLPvTableComponentElement: {
        prototype: HTMLPvTableComponentElement;
        new (): HTMLPvTableComponentElement;
    };
    interface HTMLElementTagNameMap {
        "my-component": HTMLMyComponentElement;
        "pv-legend-component": HTMLPvLegendComponentElement;
        "pv-table-component": HTMLPvTableComponentElement;
    }
}
declare namespace LocalJSX {
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface PvLegendComponent {
        /**
          * The legend items
         */
        "items"?: LegendItem[] | string;
        /**
          * The legend title
         */
        "legendTitle"?: string;
    }
    interface PvTableComponent {
        /**
          * The table column definitions
         */
        "columns"?: TableColumn[] | string;
        /**
          * The table data
         */
        "data"?: any[] | string;
        /**
          * Enable row deletion
          * @default false
         */
        "enableRowSelection"?: boolean;
        /**
          * Items to display per page
          * @default 5
         */
        "itemsPerPage"?: number;
        "onActionDelete"?: (event: PvTableComponentCustomEvent<any>) => void;
        "onRowClick"?: (event: PvTableComponentCustomEvent<any>) => void;
        "onRowSort"?: (event: PvTableComponentCustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "my-component": MyComponent;
        "pv-legend-component": PvLegendComponent;
        "pv-table-component": PvTableComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
            "pv-legend-component": LocalJSX.PvLegendComponent & JSXBase.HTMLAttributes<HTMLPvLegendComponentElement>;
            "pv-table-component": LocalJSX.PvTableComponent & JSXBase.HTMLAttributes<HTMLPvTableComponentElement>;
        }
    }
}
